# Generated by Django 4.1 on 2024-05-18 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='folder_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.folders'),
        ),
    ]
