# Generated by Django 4.1 on 2024-05-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_places_folder_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folders',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='places',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
